### ISSUE TITLE
Add ability to configure login/password for new installations

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#10]
This should probably go in the `.env` file as this looks like the only file that users will edit.

**Comment by GreatYYX** [comment]
@szeke I thought about integrating configs before, but it's not that easy to move all settings into an env file for some are in python files, some are in plain text file, some of the settings are not key-value pairs. But yes, we can move some important settings which will be set by user to env file like the number of etk workers.
For username and password tokens, I don't know if we can integrate all of them into env. 1. For DIG APP use nginx to store them (in .htpasswd), landmark tools don't have authentication, mydig webservices use python file (which can read variable from environment). 2. Besides, the tokens also need to be include in the inter-service requests, all of services are hard coded in request base url (e.g. `http://user:pass@example.com/`). Under this condition, change username and password is really a big work.
So, one of the solution for unifying is set all of the exposed services behind nginx and let nginx do authentication (solve p1), we don't need any authentication in inner network (solve p2). This will also hide many ports which are required to expose without nginx, docker-compose can only handle exposing (to a fixed / random) port or not. But under this solution, username and password are still in `.htpasswd` file, not env file.

**Comment by GreatYYX** [comment]
One way to set env variables to `.htpasswd` file is: extend nginx image, add a script to read variables from env and write then into `.htpasswd`, then fires up nginx process.

**Comment by szeke** [comment]
If we have nginx, can we eliminate the myDIG login page?

**Comment by GreatYYX** [comment]
@jasonslepicka Thanks for advise. @szeke Yes, all the web service will use the same Nginx to do authentication, no need to implement authentication mechanism in web services anymore.

**Comment by GreatYYX** [comment]
All the services are behind Nginx now.
Two more things to do:
1. extend official Nginx image to support setting user:pass in env.
2. unify prefix of routes of Landmark tool and DIGUI.
