### ISSUE TITLE
Support document filters in ETK

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#100]
Add ability to filter out unwanted documents so that they don't appear in the KG in ES. The initial version will support simple filters based on regex. The filters will be specified in a JSON document with the following structure. At the top level, the filters are a dictionary based on TLD, so that it is easy to organize filters, and so that ETK can quickly find the filters relevant to a document.

```
{ 
  "tld1": [ ... ],
  "tld1": [ ... ],
  ...
}
```

Each of the arrays contains individual filters with the following format:

```
{
  "field": < any field in a CDR document, typically url, raw_content >,
  "regex": < a regular expression in Python syntax >, 
  "action": < one of "keep", "discard" >
}
```

When a document comes in, ETK will find the array of rules for the TLD, if the TLD is not listed, the document is `no_action`.

ETK will then test each of the rules in the array sequentially, and will do the action of the first rule whose regex is satisfied. If none of the rules apply, the document is marked as `no_action`.

**Results:**, the outcome of rule execution is recorded in the attribute `prefilter_filter_outcome`, with values `keep`, `discard` or `no_action`. 

We envision that more filtering may happen inside ETK, so that a document that the prefilter marks as `no_action` may eventually be discarded by further analysis. Downstream filters may even discard a document that the prefilter decides to keep.

**Note:** Upon ingesting the filter dictionary, ETK should compile the regexes for efficient execution.

**Comment by saggu** [comment]
We have a better way to do this in ETK2
