### ISSUE TITLE
Add myDIG routes and GUI to upload document filters.

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#101]
The actions tab should provide a buttons to download and upload document filters. 

The back-end should check that the syntax is valid, e.g. the file has the correct attributes, and the regexes don't throw exceptions when compiled.

Maybe we should use JSON schema to validate the syntax: http://json-schema.org/

**Comment by GreatYYX** [comment]
@saggu myDIG will create a field named `filters` in the root of CDR object.
```
{
  "filters": {
    "tld1": {...},
    ...
  },
  ...
}
```

**Comment by saggu** [comment]
See the description in https://github.com/usc-isi-i2/dig-etl-engine/issues/100
