### ISSUE TITLE
Add support for extraction black-lists in myDIG

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#104]
Add ability to associate black-list glossaries with fields.

We discussed with @GreatYYX about including the blacklists in the field editor similar to the way that spacy rules can be added. It would be more uniform to use glossaries, but either way is fine as long as the data gets into myDIG.

When a field black list is uploaded, myDIG will query elastic search to retrieve all the pages that contain the bad extractions and put them in the kafka topic so that they get reprocessed. myDIG should remove the KG from the document before adding to the kafka topic.

myDIG needs to save the black-lists as glossaries, eg `<fieldname>-blacklist.txt` so that ETK can find them an load them.

ETK should reprocess the document from scratch, and after extraction, check the black lists and lower the confidence of the blacklisted extractions to a low number, eg, 0.1. The offending extractions should not be removed as we may need to bring them back if we remove them by mistake.

**Comment by szeke** [comment]
Assigning to both @saggu and @GreatYYX as there is work from both.

**Comment by saggu** [comment]
the work on etk side is already complete.
