### ISSUE TITLE
INF 558 Issue : Docker compose file invalid with new update

### ISSUE THREAD

**Issue by anand-prashar** [usc-isi-i2/dig-etl-engine#106]
I am a student of Professor Pedro in USC.

Previous version of docker-compose was working fine with mobyLinuxVM docker.
I am unable to initiate any docker images updates with new config file.

I am still able re-download images with precious clone of this project.

Attached:
1. Powershell error console showing error on new pull; and working fine on previous pull
2. docker compose.yml from previous pull ( uploading as txt, yml not allowed)

Please reach me at: aprashar[AT]usc.edu
[docker-compose.txt](https://github.com/usc-isi-i2/dig-etl-engine/files/1490671/docker-compose.txt)

![dig-etl-engine error](https://user-images.githubusercontent.com/9823261/33063642-e7ccf9c4-ce57-11e7-885e-08593a4b0749.PNG)

**Comment by szeke** [comment]
@GreatYYX please take a look at this problem. @anand-prashar did you try again, maybe it was a network problem

**Comment by GreatYYX** [comment]
@anand-prashar I think you don't have .env file

**Comment by anand-prashar** [comment]
Update: Github won't accept large attachments.

Here, it is on drive :
https://drive.google.com/drive/folders/1QPRIwghip1yx-bn7dwqH1zoadvIA3QAG?usp=sharing

**Comment by anand-prashar** [comment]
@szeke , yes i did; but it wont work even after system restart
@GreatYYX , i am not sure what you mean. I cloned it as-is.

Please refer to attachment url above

**Comment by anand-prashar** [comment]
![final errors](https://user-images.githubusercontent.com/9823261/33097664-bdc1d808-cebf-11e7-9cab-3c00e38e2703.PNG)
[Final Errors.txt](https://github.com/usc-isi-i2/dig-etl-engine/files/1493020/Final.Errors.txt)

Thank you @GreatYYX  for quickly observing that.

Install started perfectly. Unfortunately, at the end, i think it failed to create containers
with message "Drive not shared".

Please see attached snap, and complete log of installation.

![final errors](https://user-images.githubusercontent.com/9823261/33097657-b80701cc-cebf-11e7-96eb-8720cfa005de.PNG)

**Comment by anand-prashar** [comment]
@GreatYYX , nevermind. Docker was requesting access for some containers. It is starting now.

I am closing this thread.

Thank you for prompt reply
