### ISSUE TITLE
Bug in import project

### ISSUE THREAD

**Issue by GreatYYX** [usc-isi-i2/dig-etl-engine#107]
when there's a custom_etk_config.json

**Comment by anand-prashar** [comment]
@GreatYYX , can you please elaborate ? I think, I am facing similar issue.

I tried to use import the provided project 'events', and use provided datasets too. No records are getting added even after hitting 'Recreate Knowledge Graph'. Attached.

Will it work, if i do not import the project, just instead follow steps in advanced tutorial ?

![bug](https://user-images.githubusercontent.com/9823261/33235172-ad268842-d1e7-11e7-8bfe-1a645b510bb0.PNG)

**Comment by GreatYYX** [comment]
This problem is fixed in the latest release (mydig_ws 1.1.2). I need to close it now.

For your issue, I think you forgot to increase the `Desired number`. Try to set it to 10, turn on pipeline (or recreate knowledge graph if it's the first time), after a while, you should see something in KG. If it's still there, please create another issue.
