### ISSUE TITLE
Problem with importing Events project in MyDig

### ISSUE THREAD

**Issue by ikow** [usc-isi-i2/dig-etl-engine#108]
Hi,
I'm a student in inf558. Same problem with @anand-prashar, I tried to run the example project "events" following "myDIG Advanced User Guide" but failed to create Knowledge Graph yesterday. When I hit "recreate knowledge graph", no knowledge graph was created. I set the desired number to 10. Am I using the wrong version of dig? Thanks.
@szeke  @GreatYYX

**Comment by szeke** [comment]
I'll take a look this afternoon, did you get the latest version of DIG? Also, when you create the KG, you get the confirmation that says "Mapping recreated and data is being added"?

What is in your `working_dir/etk_stdout_0.txt`

**Comment by ikow** [comment]
Hi Professor Pedro,
Thank you for your quick reply.
I pulled MyDig on last Friday.I got the confirmation and the "working_dir/etk_stdout_0.txt" file is empty.

**Comment by GreatYYX** [comment]
@ikow Please pull again since some bugs had been fixed yesterday. 

Here are couple of things need to be check:
1. Make sure you have enough memory. If you are using MAC or Win, the size of memory you set is the maximum size VM can use, not the actual size you have. (Additionally, try to set both `NUM_ETK_PROCESSES` and `KAFKA_NUM_PARTITIONS` to 1).
2. After clicking `recreate mapping` button, you should get the confirmation which indicates mapping recreated and data is being added in backend. Ensure pipeline is on. Ensure desired number is not 0.
3. `curl -u <user>:<password> http://<url>:<port>/es/_cat/indices?v`, you should see an index of your project.
4. Since there's no output in etk_stdout, maybe the Kafka is not working properly, use `docker ps | grep kafka` to find out if Kafka is running; if not, there should be some error logs in `docker logs dig_kafka_1`.

**Comment by anand-prashar** [comment]
My problem remains unresolved. But let me try the steps you just posted. Will update here.
BTW, i know of atleast 2 other teams facing same problem.

Thank you @szeke , @GreatYYX  for helping out in weekend.

**Comment by ikow** [comment]
Thanks. @GreatYYX 
I changed the settings in .env file for NUM_ETK_PROCESSES and KAFKA_NUM_PARTITIONS and the screenshot is as follows:

<img width="842" alt="screen shot 2017-11-26 at 3 24 35 pm" src="https://user-images.githubusercontent.com/5469411/33245553-42587142-d2be-11e7-8448-a8773fef4fc4.png">

After excuted "docker logs dig_kafka_1", I got an INFO message having an unknown error shows as follows:

[2017-11-26 23:01:24,262] INFO Opening socket connection to server dig_zookeeper_1.dig_dig_net/172.19.0.6:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2017-11-26 23:01:24,319] INFO Socket connection established to dig_zookeeper_1.dig_dig_net/172.19.0.6:2181, initiating session (org.apache.zookeeper.ClientCnxn)

**Comment by anand-prashar** [comment]
@GreatYYX , @GreatYYX  @ikow 

Here is a similar result of curl.
![capture](https://user-images.githubusercontent.com/9823261/33245818-a9ac65bc-d2c1-11e7-914b-ddaba02d7d2d.PNG)


Also, please watch this 3 min video at 720p. I recorded the steps to run with provided project and data files. Result is same even if i manually create project.

https://www.youtube.com/watch?v=TITWOnRCYMI&feature=youtu.be

Thanks!

**Comment by GreatYYX** [comment]
@anand-prashar for you particular case, your desired number is 0. On the right side of Action, type in 10 and click "update all" button.

**Comment by anand-prashar** [comment]
@GreatYYX , you mean the value in "desired number of docs to run per TLD" ?

It remains 10. This is a snap from video i previously posted.

![capture](https://user-images.githubusercontent.com/9823261/33245915-045487c8-d2c3-11e7-8f99-4dd07d0764f2.PNG)

**Comment by GreatYYX** [comment]
@anand-prashar sorry about the confusion, but the input box here is used to set the desired number of each TLD, after clicking "update all", you should see the number in column "KG".

**Comment by GreatYYX** [comment]
@ikow Hmmm, there are just INFO messages not ERROR. I think the problem is in Kafka if all your other steps are correct, please do `docker-compose down` and restart etl-engine.

**Comment by anand-prashar** [comment]
@GreatYYX , Yes it worked. I see results in elastic search now.

Thank You for assisting !!!

[Note to other person facing same issue]
Please give enough RAM to docker, and 'update TLD' before hitting Recreate Knowledge Graph button.

**Comment by ikow** [comment]
@GreatYYX  Thank you!  It works now.

**Comment by GreatYYX** [comment]
@ikow @anand-prashar OK great! Just to clarify, you can set your desired number any time (before or after recreating mapping) you want.
