### ISSUE TITLE
doc_id for nested objects should be computed from their JSON

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#112]
The algorithm for computing the ID is as follows:

- If `doc_id` is supplied in the config as the value of a JSON path, set X to the value of JSON path. If the JSON path returns an array, use the first element.
- Trim X of leading and trailing whitespace
- If X contains only alphanumeric and underscore, use it as is, otherwise hash it and log a warning. It would be nice if we don't have to do the hashing as it is likely to break someone's logic
- Otherwise, the system should parse the JSON, write it as a string with keys sorted, and then hash it.

**Comment by GreatYYX** [comment]
please refer to #113
