### ISSUE TITLE
If the json_paths in etk configs are invalid, report an error

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/dig-etl-engine#119]
Check if the library supports such a feature

**Comment by szeke** [comment]
We should upgrade to https://github.com/h2non/jsonpath-ng because we need some of the features in it such as the ? argument that is part of the standard and not supported by the -rw version

**Comment by saggu** [comment]
Upgraded to jsonpath_ng and etk throws an error now if any of the json_paths are invalid
