### ISSUE TITLE
Add ability for fields to have segments, to start every field has three segments: url, title, description.

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#12]

**Comment by saggu** [comment]
@GreatYYX is this still relevant or has it been implemented?

**Comment by GreatYYX** [comment]
haven't fully implemented. Most cards in https://github.com/usc-isi-i2/dig-etl-engine/projects/1 need to be implemented in new GUI.

**Comment by saggu** [comment]
Obsolete in ETK2
