### ISSUE TITLE
Update field gui to display segments and extractors

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#13]
There will be a two column table:

* segment name shows the JSON path for the segment
* the second column shows the associated extractors

Each row has an 

* edit button to open a dialog the select extractors, and to edit the JSON path (should validate that JSON path is syntactically valid)
* delete button to delete the segment

Above the table is a Add Segment button.

**Comment by szeke** [comment]
The extractors are:

* all our predefined extractors
* spacy rules
* glossary

**Comment by szeke** [comment]
Working on extractors will be the next big thing for Sherya to work on

**Comment by saggu** [comment]
I think this is obsolete in etk2
