### ISSUE TITLE
Delete a project

### ISSUE THREAD

**Issue by GreatYYX** [usc-isi-i2/dig-etl-engine#130]
- stop etk
- clean up kafka topic
- delete logstash config
- delete es data
- delete all files and data
- delete from external dependencies (sandpaper, landmark tool)

**Comment by GreatYYX** [comment]
I don't know if "delete" or "overwrite" is provided by those external dependencies (e.g., landmark tool). Because user may create a new project which has the same name as the deleted one. A better way to handle this function might be: release all resources (es data, etk processes) and hide this project and forbid user to create a new project with previous name. @szeke

**Comment by szeke** [comment]
I think we should keep it simple, deleting a project should just delete the project, ie, everything in myDIG about this project. External dependencies may not get cleaned up, but what can we do.

I think a common use case will be to delete a project and then re-create it fresh with the same name to start over. We should allow this.
