### ISSUE TITLE
Filter IFPs and forecasts to keep only the ones needed for IARPA

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#140]
Implement appropriate filtering code according to specs in #134

**Comment by adityasundaram** [comment]
Script is ready with filtering code added. [https://github.com/usc-isi-i2/sage-research-tool/blob/master/parsers/prediction_set.py](get prediction sets)

**Comment by adityasundaram** [comment]
Also a module for slack client - https://github.com/usc-isi-i2/sage-research-tool/blob/master/parsers/slack_client.py
