### ISSUE TITLE
How to change the directory to save downloaded files when docker-compose up for the first time

### ISSUE THREAD

**Issue by dreamysx** [usc-isi-i2/dig-etl-engine#146]
Our server has one small root drive and one large mounted disk. I installed myDIG on the mounted disk, and changed the path in .env file to the path of mounted disk. But when I ran docker-compose up for the first time, all files were downloaded to the root drive. As a result, it returned ERROR: failed to register layer: Error processing tar file(exit status 1): write /usr/src/app/node_modules/hydrolysis/node_modules/acorn/LICENSE: no space left on device.

**Comment by szeke** [comment]
@GreatYYX please explain to @dreamysx how to solve this problem.

**Comment by GreatYYX** [comment]
@dreamysx If you are using linux, you can create a symbolic link for docker directory. Stop docker, move all files under `/var/lib/docker` to your external storage and create a link to it.

**Comment by dreamysx** [comment]
It works. Thank you.
