### ISSUE TITLE
Dev dig-etl-engine error while running ETK 

### ISSUE THREAD

**Issue by majidghgol** [usc-isi-i2/dig-etl-engine#148]
I get the following error in ETK log while recreating the knowledge graph for an ATF document. I imported the project settings as in ATF project in sandbox.

```
Traceback (most recent call last):
  File "/app/dig-etl-engine/run_core_kafka.py", line 51, in run_serial_cdrs
    result = index_knowledge_graph_fields(result)
  File "/app/miniconda/envs/etk_env/lib/python2.7/site-packages/digsandpaper/elasticsearch_indexing/index_knowledge_graph.py", line 85, in index_knowledge_graph_fields
    indexed[pred]["high_confidence_keys"] = list(indexed[pred]["high_confidence_keys"])
KeyError: 'description'
```

**Comment by majidghgol** [comment]
The document I'm getting the error on.
[armslist_test.jl.zip](https://github.com/usc-isi-i2/dig-etl-engine/files/1572868/armslist_test.jl.zip)

**Comment by jasonslepicka** [comment]
@majidghgol can we close this issue then?

**Comment by majidghgol** [comment]
@jasonslepicka I just left it open for you to decide whether exception handling would be necessary for this case or not.
