### ISSUE TITLE
Add option to delete values

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#153]
In `dig_tabular_import.py`, add ability to delete values from the CSV so that they don't appear in the JSON document. This option is necessary to delete values that are often used to code that there is no value.

The `delete` option contains a list of values that should be deleted. For example, the following deletes value `NULL` from the `District` column in ICEWS
```
{
        "path": "DISTRICT",
        "field": "state",
        "delete": [ "NULL" ]
}
```

**Comment by saggu** [comment]
This is obsolete, we do not use dig_tabular_import anymore
