### ISSUE TITLE
use a translation dictionary as post filter

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#157]
A translation dictionary translates extracted values into other values before adding them to the KG. The design goal is to make these dicts powerful and convenient to write.

Translation dicts have the following format:
```
{
  "key1": "value1",
  "key2": "",
  "key3": ["value3a", "value3b"]
}
```
When a key translates to the empty string, it means that the value should be deleted.

If a key maps to multiple values, then all values are added to the KG.

In addition, we need a config option `default_action` to specify what to do when an extracted value is not in the dictionary. The options are:

- `preserve`, put the extracted value is in the KG
- `delete`, delete the extracted value

**Comment by saggu** [comment]
An update on the  specification ,
Translation dicts have a slightly updated format
```
{
  "key1": "value1",
  "key2": ""
}
```
~~When a key translates to the empty string, it means that the value should be deleted.~~ When a key translates to empty string, action is defined by the global `remove_blank_fields` setting

**Comment by saggu** [comment]
Done, closing this issue
