### ISSUE TITLE
Automate ingestion of gold prices

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/dig-etl-engine#164]
https://www.gold.org/data/gold-price#

**Comment by saggu** [comment]
[Gold_Prices.xlsx](https://github.com/usc-isi-i2/dig-etl-engine/files/1613460/Prices.xlsx)

**Comment by fredzilla** [comment]
We should get this data from quandl.com/collections/markets/gold

**Comment by SukritiSharma** [comment]
Code merged for the this issue. 
data being pulled from http://www.quandl.com/api/v1/datasets/LBMA/GOLD.csv
which is the href for the csv in the https://www.quandl.com/collections/markets/gold
mapping files are under 
https://github.com/usc-isi-i2/sage-research-tool/tree/master/datasets/usgold
