### ISSUE TITLE
Automate ingestion of REIGN data

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/dig-etl-engine#165]
<del>https://docs.google.com/spreadsheets/d/1mrtORyhXw9TJMBYLAGPrikA4VDpla_Eq7L-NsEQ5VXg/edit#gid=1690064134

Political data
</del>

**Comment by saggu** [comment]
http://oefresearch.org/datasets/reign

**Comment by GreatYYX** [comment]
Need to write a custom script to download google sheet, URL is here https://docs.google.com/spreadsheets/d/1mrtORyhXw9TJMBYLAGPrikA4VDpla_Eq7L-NsEQ5VXg/edit#gid=1823216053, could use google api: https://developers.google.com/sheets/api/quickstart/python

**Comment by GreatYYX** [comment]
no need to use api anymore, use this url: https://docs.google.com/spreadsheets/d/1mrtORyhXw9TJMBYLAGPrikA4VDpla_Eq7L-NsEQ5VXg/pub?output=xlsx .
@szeke 's script need to support getting data from a certain sheet from a xls/xlsx file.
