### ISSUE TITLE
Automate ingestion of Japan approval data

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/dig-etl-engine#168]
https://www.nhk.or.jp/bunken/yoron/political/2007.html
https://www.japanmacroadvisors.com/page/category/politics/cabinet-approval-rating/

**Comment by Akira55** [comment]
Although "SAGE Data Sources Status" says this is event data, it seems time series data (Cabinet Approval Rating over time). 

Also, the link to NHK(the first one) does not provide CSV file (only HTML). The other one offer CSV file but they require to sing up.  How should I deal with this?

**Comment by GreatYYX** [comment]
@Akira55 file downloader will download all the data, custom script only needs to focus on data parsing and extraction.
