### ISSUE TITLE
The count of docs in ES is sometimes 0, but docs are there

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#17]
When running in ht_landmark, some of the counts become non-zero, and afterwards change to zero

**Comment by szeke** [comment]
![2017-10-04_18-05-27](https://user-images.githubusercontent.com/1074599/31206916-c280e6b4-a92f-11e7-884c-be904b630515.png)

**Comment by GreatYYX** [comment]
Bugs in es query, will be fixed in v1.0.5.
