### ISSUE TITLE
Automate Ingestion of SEA ice measurements

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/dig-etl-engine#173]
Link -http://nsidc.org/data/masie
[masie_4km_allyears_extent_sqkm.xlsx](https://github.com/usc-isi-i2/dig-etl-engine/files/1616977/masie_4km_allyears_extent_sqkm.xlsx)

**Comment by szeke** [comment]
Assigned to Mahboobeh, she doesn't have

**Comment by GreatYYX** [comment]
need to support ftp
