### ISSUE TITLE
Automate Ingestion of usgs earthquake data

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/dig-etl-engine#175]
https://earthquake.usgs.gov/fdsnws/event/1/query.csv?starttime=2017-01-02%2000:00:00&endtime=2018-01-09%2023:59:59&minmagnitude=2.5&orderby=time

**Comment by saggu** [comment]
Sample file
[Sample earthquake data file](https://github.com/usc-isi-i2/dig-etl-engine/files/1616251/earthquake_sample.xlsx)

**Comment by szeke** [comment]
There is an RSS feed of earthquakes which may be easier to use as it comes in JSON
https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.atom

**Comment by saggu** [comment]
The above link returns an xml file, or did I miss something ?

**Comment by szeke** [comment]
This data is not a time series. Majid will model it as events
