### ISSUE TITLE
Automate ingestion of asylum seekers data

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/dig-etl-engine#178]
Link - http://popstats.unhcr.org/en/asylum_seekers_monthly
Sample data:
[unhcr_popstats_export_asylum_seekers_monthly_2018_01_09_210022.xlsx](https://github.com/usc-isi-i2/dig-etl-engine/files/1617004/unhcr_popstats_export_asylum_seekers_monthly_2018_01_09_210022.xlsx)

**Comment by Akira55** [comment]
I found that this data has Month and Year in separated columns.
Do we have any way to handle this kind of data?

I guess that `extractSpreadsheet.py` timestamp is in the single column.
