### ISSUE TITLE
Desired count should be set to what user types in

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#18]
Currently there is some weird logic where it calculates the count in some funny way.

If the new count is smaller, then unmark enough docs in the catalog to reduce count to the desired amount.

If the new count is higher, then mark enough docs to meet the count. If there are not enough, then stop. Do not automatically reduce the desired count to the number of existing docs

**Comment by szeke** [comment]
The following screenshot shows that sometimes the counts are very wrong. For example `usasexguide` stayed at 200 even though I set the counts to 10.

![image](https://user-images.githubusercontent.com/1074599/31527970-70ee6fc2-af85-11e7-9c57-f071fb0c9da9.png)

**Comment by GreatYYX** [comment]
will be added in next release
