### ISSUE TITLE
Things to do for DIG UI

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/dig-etl-engine#209]
1. Have a flag to choose keywords search or form search and enable one by default
2. Have  an option to hide timeline
3. From the master config, update the email where the support message is sent
4. Change the wording in `Contact DIG / Memex Support` to `Contact us`
5. When we click `DIG` on top left corner, it goes to a 404 page, should go to home page of the project
6. Remove the option to image search in the search form (button and link search)
7. Remove images from facets
8. If a line has 2 <br/> in description, show it accordingly in DIG UI
9. Do a proper word wrap in description

**Comment by ThomasSchellenbergNextCentury** [comment]
@saggu Questions:
2. Which timeline?  There are multiple in the app.
6. and 7. @szeke already asked me about this and we decided to add options to the MyDIG project configuration.  Has Yixiang done this yet?
8. If a line has 2 what?  Newlines?
9. I implemented this months ago with <br>.  Is it not working now?

**Comment by szeke** [comment]
2. The timeline at the top of the search page
6, 7. Yes, we talked about it. Yixiang has not added the flags, will do first thing today @GreatYYX 
8. Yes, 2 new lines. Looks like when there are two new lines not to line breaks in the display. The algorithms should be to generate as many <BR> as there are new lines as we are taking care on our end to remove redundant newlines
9. In the current GUI, the interface breaks lines in the middle of words, it should break in word boundaries as is the normal case in most web sites.

**Comment by ThomasSchellenbergNextCentury** [comment]
@szeke 
So, to clarify, I need to support both `\n` and `<br>` now?  Because I had asked you if I needed to do that a few months ago and you told me No.
Also, can you please give me an example (link) where it is breaking mid-word?  It should only do that with excessively long words (like long links).

**Comment by szeke** [comment]
On the \n vd br we can do either one on our end. Tell us which one to do

**Comment by szeke** [comment]
![2018-03-05_12-48-50](https://user-images.githubusercontent.com/1074599/36999033-bc980a3c-2073-11e8-9dbd-f967f9c38aab.png)

Notice that the work INDEPENDENT is broken at the end of the line

**Comment by szeke** [comment]
![2018-03-05_12-51-27](https://user-images.githubusercontent.com/1074599/36999100-f2187796-2073-11e8-9301-56bb25f67208.png)
 Make the window smaller, gets broken differently

**Comment by ThomasSchellenbergNextCentury** [comment]
@szeke When we discussed the newline issue previously, you said that all of the HT data would use breaks (`<br>`).  Assuming that's still the case, can we make the data for your other projects match the HT data (and use break instead of newline)?

**Comment by saggu** [comment]
@ThomasSchellenbergNextCentury I tried that, the issue is, even if there are 2 \<br\>s, DIG UI just displays one line break.

**Comment by ThomasSchellenbergNextCentury** [comment]
How about we make it configurable in MyDIG then?

**Comment by saggu** [comment]
> How about we make it configurable in MyDIG then?
For the line breaks? Can we not show as many line breaks as there are \<br\>s ?

**Comment by ThomasSchellenbergNextCentury** [comment]
@saggu Oh, I misunderstood your comment.

Yes, I can update the UI to show multiple consecutive `<br/>` breaks correctly.  Are we concerned if there are, for example, 10 breaks in a row?  Should it max-out at 2?

**Comment by saggu** [comment]
@ThomasSchellenbergNextCentury we do that(maxing out at 2) currently in myDIG, but it never hurts to add another safe guard. Maxing out at 2 is a good idea.

**Comment by szeke** [comment]
@ThomasSchellenbergNextCentury I suggest that the GUI does not check for more than 2, and does what is in the data, so if we want 57 line breaks it will do them. It is up to the KG part to figure out how many to put in there.

**Comment by ThomasSchellenbergNextCentury** [comment]
Understood.

**Comment by saggu** [comment]
Closing this  DIG HT issue
