### ISSUE TITLE
When I start/stop etk processes on project `sage_kg_v2`, same action is applied to project `sage_kg`

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/dig-etl-engine#228]

**Comment by GreatYYX** [comment]
found this bug and fixed last week, haven't release a new version.

**Comment by GreatYYX** [comment]
just realized this fix is in v2 branch, not in dev.

**Comment by GreatYYX** [comment]
fixed in https://github.com/usc-isi-i2/dig-etl-engine/commit/427fdf97001510a4e9202c0f2b15598302bff3ba
