### ISSUE TITLE
in mydig, add ability to upload csv files

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/dig-etl-engine#239]
When a csv file is uploaded:

1. mydig should accept the file
2. store the file in a directory `user_uploaded_files`
3. create a CDR object and store the path of the newly uploaded file in a field `raw_content_path`
4. Pass this CDR to the ETK module(s)
5. ETK modules should handle the case where it'll have to read the file from disk.

**Comment by saggu** [comment]
This has been implemented. Tested with only csv files. Needs to be tested with any file format; tsv, xls, xlsx etc

**Comment by briantdu777** [comment]
I understand the code that is provided, but I am unsure of where this code needs to lie, whether it's an existing python script or if it's a new python script under the "dig-etl-engine" folder.

**Comment by saggu** [comment]
@briantdu777 This is a sample code, not part of dig-etl-engine. You can run it form anywhere to upload a csv to DIG. It still can't be done from the frontend

**Comment by briantdu777** [comment]
@saggu Oh gotcha, I tried to run this code on a standalone python script, and it says that "requests" in the following line isn't defined:

`resp = requests.post(url, data=payload, files=files, timeout=timeout)`

that's why I thought that this code snippet needed to be placed in a certain spot.

**Comment by saggu** [comment]
just
```
import requests
```
:)
