### ISSUE TITLE
Installing DIG on windows

### ISSUE THREAD

**Issue by moissinac** [usc-isi-i2/dig-etl-engine#240]
Hello
Following your readme, I 've installed Docker with Docker Compose. My docker instance is working.
(clearly, I'm a newbie about Docker)
Then, I clone the git repository somewhere in my computer.
Then, I create a config file (.env)
Then?
Typing 
./engine.sh up
in a terminal window doesn't work, not surprisingly.
It seems to miss a step to have DIG working with Docker. But what step?
I'm searching for a while, but not finding for the moment...
Any help is welcome.

**Comment by GreatYYX** [comment]
Two solutions for windows users:
- use docker-compose directly: `docker-compose up` (replace `./engine.sh` by `docker-compose`). but plugin system will not be enabled.
- install shell simulator on windows (e.g., mingw), or if you are using windows 10, you can install ubuntu subsystem from windows app store.

**Comment by GreatYYX** [comment]
Closing. Please reopen or create a new issue if needed. I can loop a student in who is using DIG on windows.
