### ISSUE TITLE
Upgrade myDIG to Polymer2

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#25]

**Comment by GreatYYX** [comment]
Hi @shrev, can you please upgrade Polymer to v2 when you have time, we need new features which provided by v2 only.

**Comment by shrev** [comment]
Yes will do it soon

**Comment by shrev** [comment]
technology.css incompatible with polymer2 is being fixed. Components have been upgraded to polymer2.

**Comment by saggu** [comment]
@shrev can this be closed?
