### ISSUE TITLE
RuntimeError: dictionary changed size during iteration error for conjunctive query

### ISSUE THREAD

**Issue by elmaestro08** [usc-isi-i2/dig-etl-engine#272]
Need to change line 333 of the conjunctive_query.py file in mydig-webservice/ws/search folder from 
for field in json_doc[self.SOURCE][self.KG_PREFIX].keys():

to 

for field in list(json_doc[self.SOURCE][self.KG_PREFIX]):

**Comment by saggu** [comment]
Fixed wtih https://github.com/usc-isi-i2/mydig-webservice/pull/91
