### ISSUE TITLE
No fields being created when loading sample data

### ISSUE THREAD

**Issue by HeleenE** [usc-isi-i2/dig-etl-engine#273]
Hi, thanks for open sourcing this software! I've installed the engine and imported the museum-200.jl data, but when I click on the create KG button there are no fields added. Am I missing a step? 

I get the following messages in my terminal:

<img width="1280" alt="screen shot 2019-01-06 at 13 53 59" src="https://user-images.githubusercontent.com/4982949/50736197-b16fe380-11ba-11e9-8541-c2cdfbeb0f87.png">

<img width="1392" alt="screen shot 2019-01-06 at 13 48 25" src="https://user-images.githubusercontent.com/4982949/50736177-66ee6700-11ba-11e9-9258-a1a3486f94b1.png">
<img width="1392" alt="screen shot 2019-01-06 at 13 48 29" src="https://user-images.githubusercontent.com/4982949/50736178-6b1a8480-11ba-11e9-9428-912cd286ad3e.png">

**Comment by HeleenE** [comment]
I've also tried following the advanced guide, but in the UI the Facets column stays empty.

**Comment by saggu** [comment]
@HeleenE the user guide is obsolete, I will update the guide in couple of days. There are couple of significant changes, with which the user guide is incompatible atm

**Comment by HeleenE** [comment]
@saggu thank you for the fast response! I'll wait for the user guide update. Let me know if I can help, do a noob test/review of the new guide or something.

**Comment by saggu** [comment]
@HeleenE There is a new release and updated user guide. Please try now and let me know if there are any gaps.

Thanks
