### ISSUE TITLE
Put `Screen Label` and `Screen Label Plural` in one row

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#28]
Looks like this now:

![image](https://user-images.githubusercontent.com/1074599/31445081-5785ccda-ae6b-11e7-9124-2daf3c26e0b8.png)

The two fields should be in one row to make the screen more compact

**Comment by szeke** [comment]
I see this was done. The two fields should divide the space exactly in half

**Comment by shrev** [comment]
changed style so that space is divided.
