### ISSUE TITLE
What Base Images are being used?

### ISSUE THREAD

**Issue by brianda-plascencia** [usc-isi-i2/dig-etl-engine#280]
Would like to know what base images were used.

**Comment by saggu** [comment]
@brianda-plascencia all the images are listed in https://github.com/usc-isi-i2/dig-etl-engine/blob/master/docker-compose.yml

unless I misunderstood your question

**Comment by saggu** [comment]
Base images for the respective docker are defined in the docker file
etk - https://github.com/usc-isi-i2/etk/blob/master/Dockerfile
mydig-webservice -  https://github.com/usc-isi-i2/mydig-webservice/blob/master/Dockerfile
dig-etl-engine - https://github.com/usc-isi-i2/dig-etl-engine/blob/master/Dockerfile
