### ISSUE TITLE
Add ability to insert custom etk_config files into the etk config

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#30]
The design is to have an external directory that can contain multiple extension files and do the merge in memory every time etk runs

**Comment by szeke** [comment]
@lastmansleeping please document the design in the description, ie, where the files will be stored.

**Comment by szeke** [comment]
What is the status of this task?

**Comment by lastmansleeping** [comment]
Will push the code soon and create a pull request.

**Comment by szeke** [comment]
great, thx

p

**Comment by lastmansleeping** [comment]
[Commit on my fork](https://github.com/lastmansleeping/etk/commit/1634688986c07287583341731d4fc0f46a014d08). Will create a pull request once I sync up with @saggu. @GreatYYX will handle the functionality at the dig-etl-engine end. Still keeping the issue "In Progress".
