### ISSUE TITLE
Create myDIG routes to add custom extractors to a project

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#36]
There should be a list of all custom extractors. We need the usual CRUD routes:

- POST to add a new custom extractor. The input should the a PyPy URL or something like that, which can be used as the identifier of the custom extractor. We also need the version.
- DELETE to delete an existing custom extractor
- PUT updates the version
- GET to get list and info about individual extractor

**Comment by saggu** [comment]
@szeke aren't these obsolete with ETK2 ?

**Comment by szeke** [comment]
This issue is irrelevant.
