### ISSUE TITLE
Read the docs from `crawler` (kafka) topic

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/dig-etl-engine#42]
- Store the docs locally, should work in the same way as uploading files
- Mark the doc as `read_from_kafka` and process the doc in the etk pipeline
- If the user want to re run the doc, all the docs marked as `read_from_kafka` should not be stored again.

**Comment by GreatYYX** [comment]
change the way of implementation:

- [ ] consumer reads from a specific Kafka topic
- [ ] remove project field and send data to the upload endpoint in web service
- [ ] update web service to support this new design

**Comment by szeke** [comment]
status
