### ISSUE TITLE
Add the `Add To Queue` button

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#45]
In the new workflow, when user changes desired, nothing happens to the queue.

When user clicks this button, the documents are added to the queue.

When the user clicks `Recreate Knowledge Graph`, the system will clear ES, load the mapping, restart the ETK pipeline, return to browser, and fire up a process to load all the data.

**Comment by GreatYYX** [comment]
multi-processing doesn't work for mydig needs to change the mark in in-memory catalog.
Implemented by multi-threading, data will be asynchronously pushed to queue in the backend.
