### ISSUE TITLE
Cannot parse timestamp

### ISSUE THREAD

**Issue by Hellofafar** [usc-isi-i2/dig-etl-engine#60]
Hi,

When I used mydig I met a strange exception saying that "MapperParsingException[failed to parse [timestamp]]; nested: IllegalArgumentException[Invalid format: "1505194400.0" is malformed at "194400.0"];"

In my Json Line file, for every line there is a key "timestamp", for example the one caused example is "timestamp":"1505194400.0".

**Comment by GreatYYX** [comment]
According to CDR V3.1, timestamp should use ISO format: `Timestamp of COLLECTION of data from the web using ISO­8601format in UTC, eg 2017­02­15T20:30:59Z`.

**Comment by Hellofafar** [comment]
Okay, thanks!
