### ISSUE TITLE
In Spacy UI editor, delete does not behave like delete

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/dig-etl-engine#67]
If I delete the rule by pressing the `red` X, the rules are not saved. I have to click `Run Rules` to post the request

**Comment by GreatYYX** [comment]
I remember our original design is: click run rule, no matter rules are correct or not, they will be sent to backend and saved in backend, backend returns the result of execution.

That's why in GUI, only after clicking `Run rules` will the rules be saved by backend.

**Comment by saggu** [comment]
It should save on every user edit, it saves when you add part of a rule. It only does not work when you delete a rule

**Comment by szeke** [comment]
+1 on save after every user action so that users don't lose data.

**Comment by GreatYYX** [comment]
does backend need to split current endpoint to `save` and `run`?

**Comment by szeke** [comment]
I don't think so. Every action in the editor should POST the rules.

**Comment by RqS** [comment]
fixed
