### ISSUE TITLE
Pipeline turns off after several hours even when there are documents to process

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#71]
The pipeline stopped for atf, sfda and sec, even when there were docs to process. I turned them back on and the documents continued to flow. There was no need to add docs to the queue again.

The pipeline should never turn off as longs as there are docs to process.

**Comment by szeke** [comment]
status on this? close?

**Comment by GreatYYX** [comment]
I can not reproduce this error, could be out-of-memory or synchronization problem (old thread-unsafe version). Closing this thread, open it if you see it again.
