### ISSUE TITLE
Integrate table content extractor in ETK pipeline

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#84]
Add the table extractor to run by default as a content extractor.

**Comment by majidgh1991** [comment]
I updated the table content extractor in ETK and tested it in ETL-engine, it works fine. I will close this issue once the table extractor is in default ETK config.

**Comment by majidghgol** [comment]
The new table extractor code is now pushed in the development branch of etk, and is ready to use.
