### ISSUE TITLE
Add all text as another content extractor

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/dig-etl-engine#87]
While running beautiful soup to extract tables, also create a content field with all the text

**Comment by majidgh1991** [comment]
I added this in the table extractor code. Since we already are traversing all the tables there, we can delete them from html and return the text in the remaining html.

**Comment by majidghgol** [comment]
For the table extractor to return two separate output (tables and text in the page), we need some enhancements in ETK (having multiple output paths for an extractor), which is not related to this issue (as soon as we have that feature in ETK, the text can go straight in the content extraction path). So I will close this thread.
